import { useState, useEffect, useCallback, useRef } from 'react';
import { useDocumentTitle } from '../hooks/useDocumentTitle';
import { AlertTriangle, Clock, Loader2, TrendingUp, RefreshCw, Info } from 'lucide-react';
import { readinessService } from '../services/readinessService';
import { predictionService } from '../services/predictionService';
import { CATEGORY_LABELS } from '../constants/categories';

function formatRupiah(n) {
  return new Intl.NumberFormat('id-ID', {
    style: 'currency',
    currency: 'IDR',
    maximumFractionDigits: 0,
  }).format(n ?? 0);
}

function getNextMonth() {
  const now = new Date();
  const next = new Date(now.getFullYear(), now.getMonth() + 1, 1);
  return `${next.getFullYear()}-${String(next.getMonth() + 1).padStart(2, '0')}`;
}

function formatMonth(monthYear) {
  if (!monthYear) return '-';
  const [year, month] = monthYear.split('-');
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'Mei', 'Jun', 'Jul', 'Agu', 'Sep', 'Okt', 'Nov', 'Des'];
  return `${months[parseInt(month, 10) - 1]} ${year}`;
}

// Stable constant — computed once
const TARGET_MONTH = getNextMonth();

export default function PrediksiPage() {
  useDocumentTitle('Prediksi');
  const [readiness, setReadiness] = useState(null);
  const [predictions, setPredictions] = useState([]);
  const [totalPrediction, setTotalPrediction] = useState(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState('');
  const autoGeneratedRef = useRef(false); // guard: auto-generate only once

  const fetchData = useCallback(async () => {
    setLoading(true);
    setError('');
    try {
      const [readinessRes, predRes] = await Promise.all([
        readinessService.get(),
        predictionService.get(TARGET_MONTH),
      ]);
      setReadiness(readinessRes);

      // predRes is always an array of SpendingPrediction rows (or empty array)
      const predArray = Array.isArray(predRes) ? predRes : (predRes ? [predRes] : []);
      setPredictions(predArray.filter((p) => p.categorySlug !== '__total'));
      const total = predArray.find((p) => p.categorySlug === '__total');
      setTotalPrediction(total || null);
      return { readinessRes, hasPrediction: !!total };
    } catch (err) {
      console.error('Failed to fetch predictions:', err);
      setError(err?.response?.data?.message || 'Gagal memuat prediksi.');
      return { readinessRes: null, hasPrediction: false };
    } finally {
      setLoading(false);
    }
  }, []); // stable — TARGET_MONTH is module-level constant

  // Initial fetch + optional auto-generate (one-shot, guarded by ref)
  useEffect(() => {
    let cancelled = false;

    const init = async () => {
      const { readinessRes, hasPrediction } = await fetchData();

      // Auto-generate jika data cukup tapi belum ada prediksi
      if (
        !cancelled &&
        !autoGeneratedRef.current &&
        !hasPrediction &&
        readinessRes?.prediction?.status &&
        readinessRes.prediction.status !== 'no_data'
      ) {
        autoGeneratedRef.current = true;
        setGenerating(true);
        try {
          await predictionService.generate();
          if (!cancelled) await fetchData();
        } catch (err) {
          console.error('Auto-generate prediction failed:', err);
          // silent fail — user dapat klik manual
        } finally {
          if (!cancelled) setGenerating(false);
        }
      }
    };

    init();
    return () => { cancelled = true; };
  }, [fetchData]);

  const handleGenerate = async () => {
    setGenerating(true);
    setError('');
    try {
      await predictionService.generate();
      await fetchData();
    } catch (err) {
      console.error('Generate prediction failed:', err);
      setError(err?.response?.data?.message || 'Gagal membuat prediksi. Pastikan backend dan AI service berjalan.');
    } finally {
      setGenerating(false);
    }
  };

  const handleRefresh = async () => {
    await fetchData();
  };

  const getConfidenceBadge = (pred) => {
    const mv = pred?.modelVersion || '';
    if (mv.startsWith('lstm')) return { bg: 'bg-green-100', text: 'text-green-700', label: 'LSTM' };
    if (mv.startsWith('avg')) return { bg: 'bg-blue-100', text: 'text-blue-700', label: 'Rata-rata' };
    const c = pred?.confidence ?? 0;
    if (c >= 0.8) return { bg: 'bg-green-100', text: 'text-green-700', label: 'LSTM' };
    return { bg: 'bg-blue-100', text: 'text-blue-700', label: 'Rata-rata' };
  };

  const status = readiness?.prediction?.status;
  const canGenerate = status && status !== 'no_data';

  return (
    <div className="p-4 md:p-6 max-w-7xl mx-auto space-y-5">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div>
          <h1 className="text-2xl font-bold text-gray-900 flex items-center gap-2">
            <TrendingUp size={24} className="text-[#7C4A2D]" />
            Prediksi Pengeluaran
          </h1>
          <p className="text-gray-500 text-sm mt-0.5">
            Estimasi pengeluaran untuk {formatMonth(TARGET_MONTH)}
          </p>
        </div>
        <div className="flex items-center gap-2 flex-wrap">
          {/* Refresh */}
          <button
            onClick={handleRefresh}
            disabled={loading || generating}
            className="flex items-center gap-2 px-3 py-2 rounded-xl bg-white border border-[#E8D5C4] text-gray-600 hover:bg-[#FFF5E6] text-sm transition-colors disabled:opacity-50"
          >
            <RefreshCw size={14} className={loading ? 'animate-spin' : ''} />
            Refresh
          </button>

          {/* Generate Button */}
          {generating ? (
            <div className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-[#FAD4C0]/50 text-[#7C4A2D] text-sm">
              <Loader2 size={14} className="animate-spin" />
              <span>Menghitung prediksi...</span>
            </div>
          ) : canGenerate ? (
            <button
              id="btn-generate-prediksi"
              onClick={handleGenerate}
              disabled={generating || loading}
              className="flex items-center gap-2 px-4 py-2 rounded-xl bg-[#FAD4C0] text-[#7C4A2D] font-medium text-sm hover:bg-[#f5c4ac] disabled:opacity-50 transition-colors"
            >
              <TrendingUp size={14} />
              {totalPrediction ? 'Regenerate Prediksi' : 'Generate Prediksi'}
            </button>
          ) : null}
        </div>
      </div>

      {/* Error */}
      {error && (
        <div className="flex items-start gap-2 text-red-800 text-sm bg-red-50 border border-red-200 rounded-xl px-4 py-3">
          <AlertTriangle size={16} className="flex-shrink-0 mt-0.5" />
          <div>
            <p className="font-medium">Gagal menghasilkan prediksi</p>
            <p className="text-xs text-red-700 mt-0.5">{error}</p>
          </div>
        </div>
      )}

      {/* Loading full-page skeleton */}
      {loading ? (
        <div className="space-y-4">
          <div className="h-28 bg-[#FAD4C0]/40 animate-pulse rounded-2xl" />
          <div className="h-48 bg-[#FAD4C0]/40 animate-pulse rounded-2xl" />
        </div>
      ) : (
        <>
          {/* Readiness Status Banners */}
          {status === 'no_data' && (
            <div className="bg-amber-50 border border-amber-200 rounded-2xl p-5 flex items-start gap-3">
              <AlertTriangle size={20} className="text-amber-600 mt-0.5 flex-shrink-0" />
              <div>
                <p className="font-semibold text-amber-800">Data Belum Cukup</p>
                <p className="text-sm text-amber-700 mt-1">
                  {readiness?.prediction?.message || 'Minimal 1 bulan data pengeluaran diperlukan untuk prediksi.'}
                </p>
                <p className="text-xs text-amber-600 mt-2 bg-amber-100 rounded-lg px-3 py-2">
                  Catat pengeluaran Anda selama minimal 1 bulan agar prediksi dapat dihasilkan.
                </p>
              </div>
            </div>
          )}

          {status === 'limited_data' && (
            <div className="bg-[#80A1C1]/10 border border-[#80A1C1]/30 rounded-2xl p-4 flex items-start gap-3">
              <Clock size={18} className="text-[#2C5282] mt-0.5 flex-shrink-0" />
              <div>
                <p className="text-sm font-medium text-[#2C5282]">Prediksi dengan Data Terbatas</p>
                <p className="text-xs text-[#2C5282]/80 mt-0.5">
                  {readiness?.prediction?.message ||
                    `Menggunakan rata-rata dari ${readiness?.prediction?.monthsData || 1} bulan data (minimal 3 bulan untuk LSTM).`}
                </p>
              </div>
            </div>
          )}

          {status === 'enough_data' && !totalPrediction && (
            <div className="bg-green-50 border border-green-200 rounded-2xl p-4 flex items-start gap-3">
              <div className="w-2 h-2 rounded-full bg-green-500 mt-2 flex-shrink-0" />
              <div>
                <p className="text-sm font-medium text-green-800">Model LSTM Siap</p>
                <p className="text-xs text-green-700 mt-0.5">
                  Data historis cukup untuk prediksi LSTM. Klik <strong>Generate Prediksi</strong> untuk memulai.
                </p>
              </div>
            </div>
          )}

          {/* Total Prediction Card */}
          {totalPrediction ? (
            <>
              <div className="bg-white border border-[#E8D5C4] rounded-2xl shadow-sm p-5">
                <div className="flex items-center justify-between gap-4">
                  <div>
                    <p className="text-sm text-gray-500">Total Prediksi {formatMonth(TARGET_MONTH)}</p>
                    <p className="text-3xl font-bold text-gray-900 mt-1">
                      {formatRupiah(totalPrediction.predictedAmount)}
                    </p>
                    {totalPrediction.updatedAt && (
                      <p className="text-xs text-gray-400 mt-1">
                        Diperbarui:{' '}
                        {new Date(totalPrediction.updatedAt).toLocaleString('id-ID', {
                          day: '2-digit',
                          month: 'short',
                          hour: '2-digit',
                          minute: '2-digit',
                        })}
                      </p>
                    )}
                  </div>
                  <div className="text-right">
                    <span
                      className={`inline-flex items-center px-2.5 py-1 rounded-lg text-xs font-medium ${getConfidenceBadge(totalPrediction).bg} ${getConfidenceBadge(totalPrediction).text}`}
                    >
                      {getConfidenceBadge(totalPrediction).label}
                    </span>
                    <p className="text-xs text-gray-400 mt-1">
                      {totalPrediction.modelVersion?.startsWith('lstm')
                        ? 'LSTM v1 (85% akurasi)'
                        : totalPrediction.modelVersion?.startsWith('avg')
                        ? 'Rata-rata sederhana (50%)'
                        : totalPrediction.modelVersion || 'Model v1'}
                    </p>
                  </div>
                </div>
              </div>

              {/* Category Predictions */}
              {predictions.length > 0 && (
                <div className="bg-white border border-[#E8D5C4] rounded-2xl shadow-sm overflow-hidden">
                  <div className="px-5 py-3.5 border-b border-[#E8D5C4] flex items-center justify-between">
                    <h2 className="font-semibold text-gray-900 text-sm">Prediksi per Kategori</h2>
                    <span className="text-xs text-gray-400">{predictions.filter(p => p.predictedAmount > 0).length} kategori</span>
                  </div>
                  <div className="divide-y divide-[#E8D5C4]">
                    {predictions
                      .sort((a, b) => b.predictedAmount - a.predictedAmount)
                      .map((pred) => {
                        const categoryLabel = CATEGORY_LABELS[pred.categorySlug] || pred.categorySlug;
                        const confidenceBadge = getConfidenceBadge(pred);
                        const pct = totalPrediction.predictedAmount > 0
                          ? Math.round((pred.predictedAmount / totalPrediction.predictedAmount) * 100)
                          : 0;

                        return (
                          <div key={pred.id || pred.categorySlug} className="px-5 py-3">
                            <div className="flex items-center justify-between mb-1.5">
                              <span className="text-sm text-gray-900 font-medium">{categoryLabel}</span>
                              <div className="flex items-center gap-2">
                                <span className="text-sm font-semibold text-gray-700">
                                  {formatRupiah(pred.predictedAmount)}
                                </span>
                                <span
                                  className={`px-2 py-0.5 rounded text-xs ${confidenceBadge.bg} ${confidenceBadge.text}`}
                                >
                                  {confidenceBadge.label}
                                </span>
                              </div>
                            </div>
                            {/* Progress bar */}
                            <div className="h-1.5 bg-gray-100 rounded-full overflow-hidden">
                              <div
                                className="h-full bg-[#FAD4C0] rounded-full transition-all"
                                style={{ width: `${pct}%` }}
                              />
                            </div>
                            <p className="text-xs text-gray-400 mt-0.5">{pct}% dari total</p>
                          </div>
                        );
                      })}
                  </div>
                </div>
              )}

              {/* Disclaimer */}
              <div className="bg-[#FFF5E6] border border-[#E8D5C4] rounded-xl p-4 flex gap-2">
                <Info size={14} className="text-gray-400 flex-shrink-0 mt-0.5" />
                <p className="text-xs text-gray-500">
                  <strong className="text-gray-700">Disclaimer:</strong> Prediksi berdasarkan data historis dan model machine
                  learning. Hasil bisa berbeda dari pengeluaran aktual.{' '}
                  {totalPrediction.modelVersion?.startsWith('avg') &&
                    'Akurasi terbatas karena menggunakan rata-rata sederhana (kurang dari 3 bulan data).'}
                </p>
              </div>
            </>
          ) : (
            // Empty state — setelah load selesai, tidak ada prediksi, dan tidak sedang generating
            !generating && canGenerate && (
              <div className="flex flex-col items-center justify-center py-16 text-center">
                <div className="w-20 h-20 rounded-2xl bg-[#FAD4C0]/20 flex items-center justify-center mb-4">
                  <TrendingUp size={36} className="text-[#7C4A2D]" />
                </div>
                <p className="text-base font-semibold text-gray-800">Belum Ada Prediksi</p>
                <p className="text-sm text-gray-500 mt-1 max-w-xs">
                  Klik tombol <strong>Generate Prediksi</strong> di atas untuk menghasilkan estimasi pengeluaran bulan depan.
                </p>
                <button
                  onClick={handleGenerate}
                  disabled={generating || loading}
                  className="mt-5 flex items-center gap-2 px-5 py-2.5 rounded-xl bg-[#FAD4C0] text-[#7C4A2D] font-medium text-sm hover:bg-[#f5c4ac] disabled:opacity-50 transition-colors"
                >
                  <TrendingUp size={14} />
                  Generate Prediksi Sekarang
                </button>
              </div>
            )
          )}

          {/* Generating overlay state */}
          {generating && !totalPrediction && (
            <div className="flex flex-col items-center justify-center py-16 text-center">
              <Loader2 size={40} className="animate-spin text-[#FAD4C0] mb-4" />
              <p className="text-base font-semibold text-gray-800">Menghitung Prediksi...</p>
              <p className="text-sm text-gray-500 mt-1">
                Model sedang memproses data historis Anda. Mohon tunggu sebentar.
              </p>
            </div>
          )}
        </>
      )}
    </div>
  );
}
